

OBJECTS		= reciprocal.o
LIBRARIES	=
PROGRAMS	= main

.PHONY:         all clean

all:            $(OBJECTS) $(LIBRARIES) $(PROGRAMS)


clean:
	rm -f *.o $(LIBRARIES) $(PROGRAMS)

main:		reciprocal.o
