

OBJECTS		= 
LIBRARIES	=
PROGRAMS	= fork-exec fork print-pid sigchld sigusr1 system zombie

.PHONY:         all clean

all:            $(OBJECTS) $(LIBRARIES) $(PROGRAMS)

clean:
	rm -f *.o *.a $(PROGRAMS)
